backend:
  name: github
  repo: techman177/busco-tu-renta-by-jocelyn # Tu repositorio
  branch: main

media_folder: "img/propiedades" # Donde se guardarán las fotos
public_folder: "/img/propiedades"

collections:
  - name: "propiedades"
    label: "Propiedades"
    folder: "content/propiedades" # Aquí se guardará la info
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Habitaciones", name: "rooms", widget: "number"}
      - {label: "Baños", name: "bathrooms", widget: "number"}
      - {label: "Imagen Principal", name: "image", widget: "image"}
      - {label: "Descripción", name: "body", widget: "markdown"}